name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake ninja-build

    - name: Configure with CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G Ninja

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Upload built binary
      uses: actions/upload-artifact@v4
      with:
        name: mobomidiplayer-${{ matrix.os }}
        path: ${{ matrix.os == 'windows-latest' && 'build/mobomidiplayer.exe' || 'build/mobomidiplayer' }}
